# Generated by Django 5.1.6 on 2025-03-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_old_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabel',
            new_name='is_availabl',
        ),
    ]
