# Generated by Django 5.1.6 on 2025-03-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_is_availabel_product_is_availabl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availabl',
            new_name='is_available',
        ),
    ]
